/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import AboutSection from "../components/About";
import Contribute from "../components/Contribute";
import Features from "../components/Features";
import GetStarted from "../components/GetStarted";
import Header from "../components/Header";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
            </Head>

            <Header />
            <AboutSection />
            <GetStarted />
            <Features />
            <Contribute />
        </div>
    );
}
